const SET_BORROWED_BOOKS = "SET_BORROWED_BOOKS";
const SET_USER = "SET_USER";
const SET_BOOK_LIST = "SET_BOOK_LIST";
const DELETE_FROM_BORROWED_BOOKS = "DELETE_FROM_BORROWED_BOOKS";
const ADD_TO_BORROWED_BOOKS = "ADD_TO_BORROWED_BOOKS";

export {
    SET_BOOK_LIST,
    SET_BORROWED_BOOKS,
    SET_USER,
    DELETE_FROM_BORROWED_BOOKS,
    ADD_TO_BORROWED_BOOKS,
}